/* eslint-disable @typescript-eslint/ban-types */
import type { Property } from "csstype"

// eslint-disable-next-line @typescript-eslint/no-namespace
export namespace Mso {

    export type Color = Property.Color
    export type Length = number | string
    export type Percentage = string & {}
    export type Url = string & {}

    export type ColorAlt = Color | "auto" | "windowtext"
    export type FontStyle = "italic" | "normal" | "oblique"
    export type HorizAlign = "center" | "left" | "right"
    export type BorderSource = "auto" | "background" | "foreground"
    export type YesNo = "yes" | "no"
    export type Auto = "auto"

    export type BorderStyle =
        | "apples"
        | "arched-scallops"
        | "auto"
        | "baby-pacifier"
        | "baby-rattle"
        | "balloons-3-colors"
        | "balloons-hot-air"
        | "basic-black-dashes"
        | "basic-black-dots"
        | "basic-black-squares"
        | "basic-thin-lines"
        | "basic-white-dashes"
        | "basic-white-dots"
        | "basic-white-squares"
        | "basic-wide-inline"
        | "basic-wide-midline"
        | "basic-wide-outline"
        | "bats"
        | "birds"
        | "birds-flight"
        | "cabins"
        | "cake-slice"
        | "candy-corn"
        | "celtic-knotwork"
        | "certificate-banner"
        | "chain-link"
        | "champagne-bottle"
        | "checked-bar-black"
        | "checked-bar-color"
        | "checkered"
        | "christmas-tree"
        | "circles-lines"
        | "circles-rectangles"
        | "classical-wave"
        | "clocks"
        | "compass"
        | "confetti"
        | "confetti-grays"
        | "confetti-outline"
        | "confetti-streamers"
        | "confetti-white"
        | "corner-triangles"
        | "coupon-cutout-dashes"
        | "coupon-cutout-dots"
        | "crazy-maze"
        | "creatures-butterfly"
        | "creatures-fish"
        | "creatures-insects"
        | "creatures-lady-bug"
        | "cross-stitch"
        | "cup"
        | "dash-dot-stroked"
        | "dashed"
        | "dash-large-gap"
        | "dash-small-gap"
        | "deco-arch"
        | "deco-arch-color"
        | "deco-blocks"
        | "diamonds-gray"
        | "dot-dash"
        | "dot-dash-slanted"
        | "dot-dot-dash"
        | "dotted"
        | "double"
        | "double-d"
        | "double-diamonds"
        | "double-wave"
        | "earth-1"
        | "earth-2"
        | "eclipsing-squares-1"
        | "eclipsing-squares-2"
        | "eggs-black"
        | "emboss-3d"
        | "engrave-3d"
        | "fans"
        | "film"
        | "firecrackers"
        | "flowers-block-print"
        | "flowers-daisies"
        | "flowers-modern-1"
        | "flowers-modern-2"
        | "flowers-pansy"
        | "flowers-red-rose"
        | "flowers-roses"
        | "flowers-teacup"
        | "flowers-tiny"
        | "gems"
        | "gingerbread-man"
        | "gradient"
        | "groove"
        | "hairline"
        | "handmade-1"
        | "handmade-2"
        | "heart-balloon"
        | "heart-gray"
        | "hearts"
        | "heebie-jeebies"
        | "holly"
        | "house-funky"
        | "hypnotic"
        | "ice-cream-cones"
        | "inset"
        | "light-bulb"
        | "lightning-1"
        | "lightning-2"
        | "maple-leaf"
        | "maple-muffins"
        | "map-pins"
        | "marquee"
        | "marquee-toothed"
        | "medium"
        | "moons"
        | "mosaic"
        | "music-notes"
        | "none"
        | "northwest"
        | "outset"
        | "ovals"
        | "packages"
        | "palms-black"
        | "palms-color"
        | "paper-clips"
        | "papyrus"
        | "party-favor"
        | "party-glass"
        | "pencils"
        | "people"
        | "people-hats"
        | "people-waving"
        | "poinsettias"
        | "postage-stamp"
        | "pumpkin-1"
        | "push-pin-note-1"
        | "push-pin-note-2"
        | "pyramids"
        | "pyramids-above"
        | "quadrants"
        | "ridge"
        | "rings"
        | "safari"
        | "sawtooth"
        | "sawtooth-gray"
        | "scared-cat"
        | "seattle"
        | "shadowed-squares"
        | "sharks-teeth"
        | "shorebird-tracks"
        | "short-dash"
        | "skyrocket"
        | "snowflake-fancy"
        | "snowflakes"
        | "solid"
        | "solid-thick"
        | "sombrero"
        | "southwest"
        | "stars"
        | "stars-3d"
        | "stars-black"
        | "stars-shadowed"
        | "stars-top"
        | "sun"
        | "swirligig"
        | "thick"
        | "thick-thin-large-gap"
        | "thick-thin-medium-gap"
        | "thick-thin-small-gap"
        | "thick-thin-thick-small-gap"
        | "thin"
        | "thin-thick-large-gap"
        | "thin-thick-medium-gap"
        | "thin-thick-small-gap"
        | "thin-thick-thin-large-gap"
        | "thin-thick-thin-medium-gap"
        | "thin-thick-thin-small-gap"
        | "three-d-emboss"
        | "three-d-engrave"
        | "torn-paper"
        | "torn-paper-black"
        | "trees"
        | "triangle-party"
        | "triangles"
        | "tribal-1"
        | "tribal-2"
        | "tribal-3"
        | "tribal-4"
        | "tribal-5"
        | "tribal-6"
        | "triple"
        | "twisted-lines-1"
        | "twisted-lines-2"
        | "vine"
        | "wave"
        | "waveline"
        | "weaving-angles"
        | "weaving-braid"
        | "weaving-ribbon"
        | "weaving-strips"
        | "white-flowers"
        | "windowtext"
        | "woodwork"
        | "x-illusions"
        | "zany-triangles"
        | "zig-zag"
        | "zig-zag-stitch"


    export type Element =
        | "comment"
        | "comment-list"
        | "dropcap-dropped"
        | "dropcap-in-margin"
        | "endnote"
        | "endnote-continuation-notice"
        | "endnote-continuation-separator"
        | "endnote-list"
        | "endnote-separator"
        | "field-begin"
        | "field-end"
        | "field-separator"
        | "footer"
        | "footnote"
        | "footnote-continuation-notice"
        | "footnote-continuation-separator"
        | "footnote-list"
        | "footnote-separator"
        | "frame"
        | "header"
        | "none"
        | "paragraph-mark-properties"
        | "table-head"
}

/**
 *
 * @see https://stigmortenmyre.no/mso/html/concepts/ofconstyletable.htm
 */
export interface MsoProperty {
    fontColor: Property.Color
    horizAlign: "center" | "left" | "right"
    listImage1: Mso.Url
    listImage2: Mso.Url
    listImage3: Mso.Url
    msoAnsiFontSize: unknown
    msoAnsiFontStyle: "italic" | "normal" | "oblique"
    msoAnsiFontWeight: Property.FontWeight
    msoAnsiLanguage: unknown
    msoAsciiFontFamily: unknown
    msoBackground: unknown
    msoBackgroundSource: Mso.Auto
    msoBaselinePosition: unknown
    msoBidiFlag: "off" | "on"
    msoBidiFontFamily: unknown
    msoBidiFontSize: unknown
    msoBidiFontStyle: unknown
    msoBidiFontWeight: Property.FontWeight
    msoBidiLanguage: unknown
    msoBookmark: unknown
    msoBorderAlt: unknown
    msoBorderBetween: unknown
    msoBorderBetweenColor: unknown
    msoBorderBetweenStyle: Mso.BorderStyle
    msoBorderBetweenWidth: unknown
    msoBorderBottomAlt: unknown
    msoBorderBottomColorAlt: unknown
    msoBorderBottomSource: Mso.BorderSource
    msoBorderBottomStyleAlt: Mso.BorderStyle
    msoBorderBottomWidthAlt: unknown
    msoBorderColorAlt: unknown
    msoBorderEffect: "3d" | "box"
    msoBorderLeftAlt: unknown
    msoBorderLeftColorAlt: unknown
    msoBorderLeftSource: Mso.BorderSource
    msoBorderLeftStyleAlt: Mso.BorderStyle
    msoBorderLeftWidthAlt: unknown
    msoBorderRightAlt: unknown
    msoBorderRightColorAlt: unknown
    msoBorderRightSource: Mso.BorderSource
    msoBorderRightStyleAlt: Mso.BorderStyle
    msoBorderRightWidthAlt: unknown
    msoBorderShadow: Mso.YesNo
    msoBorderSource: Mso.BorderSource
    msoBorderStyleAlt: Mso.BorderStyle
    msoBorderTopAlt: unknown
    msoBorderTopColorAlt: unknown
    msoBorderTopSource: Mso.BorderSource
    msoBorderTopStyleAlt: unknown
    msoBorderTopWidthAlt: unknown
    msoBorderWidthAlt: unknown
    msoBreakType: unknown
    msoBuild: unknown
    msoBuildAfterAction: unknown
    msoBuildAfterColor: unknown
    msoBuildAutoSecs: unknown
    msoBuildAvi: unknown
    msoBuildDualId: unknown
    msoBuildOrder: unknown
    msoBuildSoundName: unknown
    msoBulletImage: unknown
    msoCellspacing: unknown
    msoCellSpecial: unknown
    msoCharIndent: unknown
    msoCharIndentCount: unknown
    msoCharIndentSize: unknown
    msoCharType: unknown
    msoCharWrap: unknown
    msoColorAlt: unknown
    msoColorIndex: unknown
    msoColorSource: Mso.Auto
    msoColumnBreakBefore: unknown
    msoColumns: unknown
    msoColumnSeparator: unknown
    msoCommentAuthor: unknown
    msoCommentContinuation: unknown
    msoCommentId: unknown
    msoCommentReference: unknown
    msoDataPlacement: "new-cell" | "same-cell"
    msoDefaultHeight: Mso.Length
    msoDefaultWidth: Mso.Length
    msoDiagonalDown: Mso.BorderStyle
    msoDiagonalDownColor: unknown
    msoDiagonalDownSource: Mso.BorderSource
    msoDiagonalDownStyle: Mso.BorderStyle
    msoDiagonalDownWidth: unknown
    msoDiagonalUp: Mso.BorderStyle
    msoDiagonalUpColor: unknown
    msoDiagonalUpSource: Mso.BorderSource
    msoDiagonalUpStyle: Mso.BorderStyle
    msoDiagonalUpWidth: unknown
    msoDisplayedDecimalSeparator: string
    msoDisplayedThousandSeparator: string
    msoElement: Mso.Element
    msoElementAnchorHorizontal: unknown
    msoElementAnchorLock: "auto" | "locked"
    msoElementAnchorVertical: unknown
    msoElementFrameHeight: unknown
    msoElementFrameHspace: unknown
    msoElementFrameVspace: unknown
    msoElementFrameWidth: unknown
    msoElementLeft: Mso.Length | ("center" | "inside" | "left" | "outside" | "right")
    msoElementLinespan: unknown
    msoElementTop: Mso.Length | ("bottom" | "inside" | "middle" | "outside" | "top")
    msoElementWrap: "around" | "auto" | "none" | "no-wrap-beside"
    msoEndnoteContinuationNotice: unknown
    msoEndnoteContinuationNoticeId: unknown
    msoEndnoteContinuationNoticeSrc: Mso.Url
    msoEndnoteContinuationSeparator: unknown
    msoEndnoteContinuationSeparatorId: unknown
    msoEndnoteContinuationSeparatorSrc: Mso.Url
    msoEndnoteDisplay: unknown
    msoEndnoteId: string
    msoEndnoteNumbering: unknown
    msoEndnoteNumberingRestart: "auto" | "each-section"
    msoEndnoteNumberingStart: unknown
    msoEndnoteNumberingStyle: unknown
    msoEndnotePosition: unknown
    msoEndnoteSeparator: unknown
    msoEndnoteSeparatorId: unknown
    msoEndnoteSeparatorSrc: Mso.Url
    msoEvenFooter: unknown
    msoEvenFooterId: unknown
    msoEvenFooterSrc: Mso.Url
    msoEvenHeader: unknown
    msoEvenHeaderId: unknown
    msoEvenHeaderSrc: Mso.Url
    msoFacingPages: Mso.YesNo
    msoFareastFontFamily: unknown
    msoFareastHint: Mso.YesNo
    msoFareastLanguage: unknown
    msoFieldChange: unknown
    msoFieldChangeAuthor: unknown
    msoFieldChangeTime: unknown
    msoFieldChangeValue: unknown
    msoFieldCode: unknown
    msoFieldLock: Mso.YesNo
    msoFillsColor: Mso.Color | "auto" | "windowtext"
    msoFirstFooter: unknown
    msoFirstFooterId: unknown
    msoFirstFooterSrc: Mso.Url
    msoFirstHeader: unknown
    msoFirstHeaderId: unknown
    msoFirstHeaderSrc: Mso.Url
    msoFontAlt: unknown
    msoFontCharset: unknown
    msoFontFormat: "other" | "truetype"
    msoFontInfo: unknown
    msoFontInfoCharset: number
    msoFontInfoType: unknown
    msoFontKerning: unknown
    msoFontPitch: unknown
    msoFontSignature: unknown
    msoFontSignatureCsbOne: unknown
    msoFontSignatureCsbTwo: unknown
    msoFontSignatureUsbFour: unknown
    msoFontSignatureUsbOne: unknown
    msoFontSignatureUsbThree: unknown
    msoFontSignatureUsbTwo: unknown
    msoFontSrc: Mso.Url
    msoFontWidth: unknown
    msoFooter: unknown
    msoFooterData: unknown
    msoFooterId: unknown
    msoFooterMargin: unknown
    msoFooterSrc: Mso.Url
    msoFootnoteContinuationNotice: unknown
    msoFootnoteContinuationNoticeId: unknown
    msoFootnoteContinuationNoticeSrc: Mso.Url
    msoFootnoteContinuationSeparator: unknown
    msoFootnoteContinuationSeparatorId: unknown
    msoFootnoteContinuationSeparatorSrc: Mso.Url
    msoFootnoteId: unknown
    msoFootnoteNumbering: unknown
    msoFootnoteNumberingRestart: unknown
    msoFootnoteNumberingStart: unknown
    msoFootnoteNumberingStyle: unknown
    msoFootnotePosition: "beneath-text" | "bottom-of-page"
    msoFootnoteSeparator: unknown
    msoFootnoteSeparatorId: unknown
    msoFootnoteSeparatorSrc: Mso.Url
    msoForeground: Mso.Color | "auto" | "windowtext"
    msoFormsProtection: Mso.YesNo
    msoGenericFontFamily: unknown
    msoGridBottom: unknown
    msoGridBottomCount: unknown
    msoGridLeft: unknown
    msoGridLeftCount: unknown
    msoGridRight: unknown
    msoGridRightCount: unknown
    msoGridTop: unknown
    msoGridTopCount: unknown
    msoGutterDirection: unknown
    msoGutterMargin: unknown
    msoGutterPosition: unknown
    msoHansiFontFamily: unknown
    msoHeader: unknown
    msoHeaderData: unknown
    msoHeaderId: unknown
    msoHeaderMargin: unknown
    msoHeaderSrc: Mso.Url
    msoHeightAlt: unknown
    msoHeightRule: unknown
    msoHeightSource: unknown
    msoHide: unknown
    msoHighlight: unknown
    msoHorizontalPageAlign: unknown
    msoHyphenate: unknown
    msoIgnore: unknown
    msoKinsokuOverflow: unknown
    msoLayoutGridAlign: unknown
    msoLayoutGridCharAlt: unknown
    msoLayoutGridOrigin: unknown
    msoLevelInherit: unknown
    msoLevelLegacy: Mso.YesNo
    msoLevelLegacyIndent: unknown
    msoLevelLegacySpace: unknown
    msoLevelLegalFormat: Mso.YesNo
    msoLevelNumberFormat: unknown
    msoLevelNumbering: unknown
    msoLevelNumberPosition: unknown
    msoLevelResetLevel: unknown
    msoLevelStartAt: unknown
    msoLevelStyleLink: unknown
    msoLevelSuffix: unknown
    msoLevelTabStop: unknown
    msoLevelText: unknown
    msoLineBreakOverride: unknown
    msoLineGrid: unknown
    msoLineHeightAlt: unknown
    msoLineHeightRule: unknown
    msoLineNumbersCountBy: unknown
    msoLineNumbersDistance: unknown
    msoLineNumbersRestart: unknown
    msoLineNumbersStart: unknown
    msoLineSpacing: unknown
    msoLinkedFrame: unknown
    msoList: unknown
    msoListChange: unknown
    msoListChangeAuthor: unknown
    msoListChangeTime: unknown
    msoListChangeValues: unknown
    msoListId: unknown
    msoListIns: unknown
    msoListInsAuthor: unknown
    msoListInsTime: unknown
    msoListName: unknown
    msoListTemplateIds: unknown
    msoListType: unknown
    msoMarginBottomAlt: unknown
    msoMarginLeftAlt: unknown
    msoMarginTopAlt: unknown
    msoMirrorMargins: Mso.YesNo
    msoNegativeIndentTab: Mso.YesNo
    msoNumberFormat: unknown
    msoOutlineLevel: unknown
    msoOutlineParent: unknown
    msoOutlineParentCol: unknown
    msoOutlineParentRow: unknown
    msoOutlineParentVisibility: unknown
    msoOutlineStyle: unknown
    msoPaddingAlt: unknown
    msoPaddingBetween: unknown
    msoPaddingBottomAlt: unknown
    msoPaddingLeftAlt: unknown
    msoPaddingRightAlt: unknown
    msoPaddingTopAlt: unknown
    msoPageBorderAligned: Mso.YesNo
    msoPageBorderArt: unknown
    msoPageBorderBottomArt: unknown
    msoPageBorderDisplay: unknown
    msoPageBorderLeftArt: unknown
    msoPageBorderOffsetFrom: unknown
    msoPageBorderRightArt: unknown
    msoPageBorderSurroundFooter: Mso.YesNo
    msoPageBorderSurroundHeader: Mso.YesNo
    msoPageBorderTopArt: unknown
    msoPageBorderZOrder: unknown
    msoPageNumbers: unknown
    msoPageNumbersChapterSeparator: unknown
    msoPageNumbersChapterStyle: unknown
    msoPageNumbersStart: unknown
    msoPageNumbersStyle: unknown
    msoPageOrientation: unknown
    msoPageScale: unknown
    msoPagination: unknown
    msoPanoseArmStyle: unknown
    msoPanoseContrast: unknown
    msoPanoseFamilyType: unknown
    msoPanoseLetterform: unknown
    msoPanoseMidline: unknown
    msoPanoseProportion: unknown
    msoPanoseSerifStyle: unknown
    msoPanoseStrokeVariation: unknown
    msoPanoseWeight: unknown
    msoPanoseXHeight: unknown
    msoPaperSource: unknown
    msoPaperSourceFirstPage: unknown
    msoPaperSourceOtherPages: unknown
    msoPattern: unknown
    msoPatternColor: unknown
    msoPatternStyle: unknown
    msoPrintArea: unknown
    msoPrintColor: Mso.YesNo
    msoPrintGridlines: Mso.YesNo
    msoPrintHeadings: Mso.YesNo
    msoPrintResolution: unknown
    msoPrintSheetOrder: unknown
    msoPrintTitleColumn: unknown
    msoPrintTitleRow: unknown
    msoPropChange: unknown
    msoPropChangeAuthor: unknown
    msoPropChangeTime: unknown
    msoProtection: unknown
    msoRotate: unknown
    msoRowMarginLeft: unknown
    msoRowMarginRight: unknown
    msoRubyMerge: unknown
    msoRubyVisibility: unknown
    msoSchemeFillColor: unknown
    msoSchemeShadowColor: unknown
    msoShading: unknown
    msoShadowColor: unknown
    msoSpaceAbove: Mso.YesNo
    msoSpaceBelow: Mso.YesNo
    msoSpacerun: Mso.YesNo
    msoSpecialCharacter: unknown
    msoSpecialFormat: unknown
    msoStyleId: unknown
    msoStyleName: unknown
    msoStyleNext: unknown
    msoStyleParent: unknown
    msoStyleType: unknown
    msoStyleUpdate: unknown
    msoSubdocument: Mso.YesNo
    msoSymbolFontFamily: unknown
    msoTabCount: unknown
    msoTableAnchorHorizontal: unknown
    msoTableAnchorVertical: unknown
    msoTableBspace: unknown
    msoTableDelAuthor: unknown
    msoTableDeleted: unknown
    msoTableDelTime: unknown
    msoTableDir: unknown
    msoTableInsAuthor: unknown
    msoTableInserted: unknown
    msoTableInsTime: unknown
    msoTableLayoutAlt: unknown
    msoTableLeft: unknown
    msoTableLspace: unknown
    msoTableOverlap: unknown
    msoTablePropAuthor: unknown
    msoTablePropChange: unknown
    msoTablePropTime: unknown
    msoTableRspace: unknown
    msoTableTop: unknown
    msoTableTspace: unknown
    msoTableWrap: unknown
    msoTextAnimation: unknown
    msoTextCombineBrackets: unknown
    msoTextCombineId: unknown
    msoTextControl: unknown
    msoTextFitId: unknown
    msoTextIndentAlt: unknown
    msoTextOrientation: unknown
    msoTextRaise: unknown
    msoTitlePage: Mso.YesNo
    msoTnyCompress: Mso.YesNo
    msoUnsynced: Mso.YesNo
    msoVerticalAlignAlt: Mso.Auto
    msoVerticalAlignSpecial: unknown
    msoVerticalPageAlign: unknown
    msoWidthAlt: unknown
    msoWidthSource: unknown
    msoWordWrap: unknown
    msoXlrowspan: unknown
    msoZeroHeight: Mso.YesNo
    navBannerImage: Mso.Url
    vndMsExcelNumberformat: unknown
}
